### ISSUE TITLE
review request

### ISSUE THREAD

**Issue by mutesihope** [mutesihope/Main-mobile#11]
Please leave a review for my current project

**Comment by Serengia** [comment]
Great job @mutesihope  . I like how the website is clean and it generally looks nice.👏 👏
To make it even better, you can consider the following:
- Vertically centering the logo and the nav links on the header element. 
- Making the contact form on the mobile version centered.
- Adding an **aria-label** on  `<nav id="mobile-nav" aria-label="Menu bar icon" class="menu">...</nav>` in your header. This will make your website more accessible by enabling screen readers to know what that button is. I think it's particularly important to have an **aria-label** in the said element as it is crucial for navigation. (I can see the contact form is well optimized for accessibility with good use of form input labels.👌👌)
